---
title: "Searching the Literature"
---

In this tutorial you will learn how to search the literature, manage the results, and pull from this database when you write papers. I give you my personal guarantee that you will use these skills over and over again in college. 

## 1. Download and install Zotero

There are several reference managers you might consider. I like [Zotero](https://www.zotero.org/) because it is free and open source. As a Duke student you can also download and install EndNote for free, but upgrades are paid once you leave Duke, so I advise students to start with Zotero.

Start by going [here](https://www.zotero.org/download/) and downloading Zotero 5 for your operating system. This download will include plugings for your word processor. Once you are done, use the links provided to install a connector for your favorite browser. This will let you grab references while searching the web.

## 2. Create a new collection

Collections are like project folders. You can organize your library by anything that makes sense to you, like class, topic, or paper.  

## 3. Run a basic search in Google Scholar

a. Leave Zotero with your new collection highlighted and switch to your brower of choice. Go to [Google Scholar](https://scholar.google.com). Search for "cash transfer impact". Use the folder icon in your browser to select a few references to import into Zotero. If you left Zotero with your new collection highlighted, you should now see these references in your specified collection.

b. Come back to Google Scholar. This time, follow one of the reference links. You might end up on a journal webpage. If you do, you should see a paper icon in your browser where the folder icon used to be. Click it. The reference should be in your collection.

## 4. Run a more advanced search in PubMed

a. Duke gives you access to lots of [research databases](http://guides.library.duke.edu/az.php). If you want to go into health research, you will become very familiar with [PubMed](http://www.mclibrary.duke.edu/pubmed). Go there now and type "cash transfer" into the main search bar. Use the folder icon to select a few of the results to import into your collection.

b. Now click on "Advanced" under the search bar. When I ran the search, PubMed found 372 results. From this summary page, run a new search for depression and go back to Advanced. You should see a much larger set of results.

c. Click "add" to add each search to the builder, keeping the "AND" operator. I got 8 results that represent the overlap between "cash transfers" AND "depression".

d. While viewing the results page, click on "Send to" and choose "Citation Manager". You can select up to 200 results. When you click create, you should get a new file in your dowloads folder. Open Zotero and use the File>>Import command to find and import this file you just downloaded. 

## 5. Use these references in a paper

a. Open up your word processor. You should see a "Zotero" add-in. 

b. Start typing. Put your cursor at the end of your first sentence (before the period). Use the Zotero add-in to add a citation. This should prompt you to select a citation style. Choose "American Psychological Association 6th". 

c. Start typing the name of the reference you want to cite (or use the dropdown to switch to the classic view to see all references). Zotero will insert the reference in your text.

d. Back in your document, hit return a few times and type "References". Then hit return again and use the Zotero add-in to add a bibliography. Boom.

e. Let's say that your professor decides she would prefer MLA style references. Fine. Use the Zotero add-in to change your document preferences. Pick MLA. Then change again to Nature.


