---
title: "MODULE 1: Introduction"
---
  
| Date | Topic |
|:---  |:---   |
| Tu Aug 29 | Introduction |
| Th Aug 31 | Searching the literature |
| Tu Sept 5 | Getting started with R, Part 1 |
| Th Sept 7 | Getting started with R, Part 2 |

<br>

## Aug 29: Introduction

Welcome to Duke! We'll review the syllabus, course format, and expectations.

## Aug 31: Searching the Literature

We'll complete [this tutorial](m1_searching.html) on searching the literature and using a reference manager.

## Sept 5: Getting Started with R, Part 1

Please read Chapters 1 and 4 of *Development as Freedom* (Piazza) prior to class. We'll begin our session with a discussion of these chapters, focusing on what we mean when we talk about "development". Then we will complete a series of [beginner tutorials on using R](m1_r1.html).

## Sept 7: Getting Started with R, Part 2

Please read the Preface and Chapter 1 of *Reimaging Global Health* (Piazza) prior to class. We'll try to answer the question, "so what in the heck is global health?". Then we'll return to the world of R and learn about [exploratory data analysis](m1_r2.html)!