---
title: "MODULE 2: The Experience of Poverty, Here and There"
---
  
| Date | Topic |
|:---  |:---   |
| Tu Sept 12 | $2.00 A Day, discussion |
| Th Setp 14 | $2.00 A Day, data |
| Tu Sept 19 | Portfolios of the Poor, discussion |
| Th Sept 21 | Portfolios of the Poor, data |
| Tu Sept 26 | Writing workshop #1 |
| Th Sept 28 | Presentation workshop #1 |

<br>

## Sept 12: $2.00 a Day

Come to class ready to discuss *$2.00 a Day*.

## Sept 14: $2.00 a Day

Go [here](m2_data_2day.html)

## Sept 19: Portfolios of the Poor

Come to class ready to discuss *Portfolios of the Poor*.

## Sept 21: Portfolios of the Poor

Go [here](m2_data_portfolios.html)

## Sept 26: Writing Workshop #1

Write a response paper that examines the nature of America's $2 a day poverty in the context of global poverty. In preparation for the first writing workshop, you should share your draft on Google Docs with me and the students assigned to your [writing group](https://docs.google.com/spreadsheets/d/1RD0U_kuBrtk0a4Pg6CdFuSiRgvk7NXRubVfCc_81J5k/edit?usp=sharing) by 5pm on Sept 22. Your peer reviews are due by 5pm on Sept 25. Your final draft is due by 5pm on Oct 3. See Piazza for more details.

## Sept 28: Presentation Workshop #1

Teams should prepare a 5-minute presentation with accompanying slide deck (please use Google Slides) on a topic related to the nature of poverty in the U.S. or globally. Peer reviews of group presentations are due by 5pm on Sept 29.