---
title: "MODULE 3: Why Are Some People and Places Poor and Sick?"
---
  
| Date | Topic |
|:---  |:---   |
| Tu Oct 3 | Why poverty, discussion |
| Th Oct 5 | Why poverty, data |
| Tu Oct 10 | FALL BREAK |
| Th Oct 12 | Screen film in class |
| Tu Oct 17 | Why sick, discussion |
| Th Oct 19 | Why sick, data |
| Tu Oct 24 | Writing workshop ##2 |
| Th Oct 26 | Presentation workshop ##2 |

<br>

## Oct 3: Why Are Some People and Places Poor?

Come to class ready to discuss:

- *Bottom Billion*, CH 2-5
- *Why Nations Fail*, CH 2 and 3
- *The Great Escape*, CH 2 and 3

You can find the readings on Piazza.

## Oct 5: Why Are Some People and Places Poor?

Tutorial TBA

## Oct 12: Film Screening

***Good Fortune***, Landon Van Soest and Jeremy Levine ([website](http://www.pbs.org/pov/goodfortune/))

## Oct 17: Why Are Some People and Places Sick?

Come to class ready to discuss:

- *Infections and Inequalities*, CH 2, 4, 10
- *Epic Measures*, CH 1-6

You can find the readings on Piazza.

## Oct 19: Why Are Some People and Places Sick?

Tutorial TBA

## Oct 24: Writing Workshop #2

Our second writing workshop is scheduled for October 24. Your assignment is to write a response paper based on the readings assigned in this module that examines why some people and places are poor and/or sick. You may focus on poverty or disease, or both. Your first draft is due by 5pm on Oct 23, and your final draft is due by 5pm on Oct 31. See the WW2 Piazza post for assignment details.  

## Oct 26: Presentation Workshop #2

Each group will have 10 minutes to present. Your peer review of group presentations is due by 5pm on Oct 27.