---
title: "MODULE 4: The Search for a Solution"
---
  
| Date | Topic |
|:---  |:---   |
| Tu Oct 31 | End of Poverty, discussion |
| Th Nov 2 | End of Poverty, data |
| Tu Nov 7 | The Idealist, discussion |
| Th Nov 9 | The Idealist, data |
| Tu Nov 14 | Universal basic income, discussion |
| Th Nov 16 | Universal basic income, data |
| Tu Nov 21 | Screen film in class |
| Th Nov 23 | THANKSGIVING BREAK |
| Tu Nov 28 | Poor Economics, discussion |
| Th Nov 30 | Poor Economics, data |
| Tu Dec 5 | Writing Workshop #3 |
| Th Dec 7 | Presentation Workshop #3 |

<br>

## Oct 31: End of Poverty

Cancelled

## Nov 2: End of Poverty

Come to class ready to discuss *End of Poverty*.

## Nov 7: The Idealist

Come to class ready to discuss *The Idealist*.

## Nov 9: Idealist

In this session we will explore the Millennium Development Goals and the Sustainable Development Goals.

## Nov 14: Universal Basic Income

In this session we will prepare for our discussion of universal basic income as well as discuss the Final Paper.

## Nov 16: Universal Basic Income

Come to class ready to discuss cash transfers and the idea of a universal basic income.

## Nov 21: Film Screening

In this session we will screen the film [*Bending the Arc*](http://bendingthearcfilm.com/).

## Nov 28: Poor Economics

Come to class ready to discuss *Poor Economics*.

## Nov 30: Poor Economics

Tutorial TBA

## Dec 5: Writing Workshop #3

Our final writing workshop is scheduled for Dec 5. Your assignment is to write a response paper based on the readings assigned in this module that examines whether it is likely that we will realize the end of extreme poverty in your lifetime. Your first draft is due by 5pm on Dec 4, and your final draft is due by 5pm on Dec 7. See the WW3 Piazza post for assignment details.

## Dec 7: Presentation Workshop #3

Each group will have 10 minutes to present.