---
title: "Syllabus"
---

<p id="nospace">
**Duke University, Fall 2017**  
**Instructor**: Eric Green, Ph.D.  
**Details**: T/Th, 3:05-4:20 PM

</p id="nospace">

Incomes are stagnant in many parts of the world, and the gap between the rich and poor has never been greater. Every year, millions of children die before their fifth birthday, mostly from preventable causes. Many more are infected with HIV, tuberculosis, or malaria, and 1 out of every 10 people on the planet live in extreme poverty. How is this still the case when, over the past few decades, the rich world has transferred approximately 2 trillion in aid to developing countries? Has it all been a waste? Money thrown down "Third word rat-holes"? Or has this money been woefully inadequate? Are there any reasons for optimism? Students will examine these and other questions by reading and discussing a selection of popular titles in global health and development. Critically, we will consider the role of the international community—and each of us as world citizens—in contributing to progress.

# What You'll Accomplish

My goal is for every student to leave this course with new perspectives on what it means to be poor and sick in this world. I will ask you to do the following: 

- consider the nature of poverty and what we mean by "development", foreign aid, and global health

- learn broad trends over time in important global health and development statistics

- gain an understanding of contemporary debates about the role of the international community in poverty alleviation, global health, and humanitarian action; and

- become familiar with evidence on "what works" to solve global health challenges and understand the basic toolkit for generating this evidence.

# What You'll Read

This seminar course is a book club on steriods. We'll read a collection of fantasic popular press titles, screen two films, explore global datasets, and share our ideas through individual writing exercises and group projects. Book clubs don't have exams, so neither do we. But there are plenty of opportunities throughout the semester to demonstrate your engagement and understanding of the topics we discuss. 

We'll start the semester by grounding ourselves in an understanding of what we mean by "global health" and "development". In ***Reimaging Global Health***, Duke grad Paul Farmer and his colleagues introduce us to the "biosocial" model as a lens for viewing the field of global health. Sticking with the theme of conceptual lenses, we'll also read Amartya Sen's landmark book ***Development as Freedom***, in which he argues that "development" is both the primary end and as the principal means of development. You'll find the assigned chapters on Sakai. 

We'll begin our deep dive this semester with two books on the experience of living in poverty at home and around the world. In ***$2.00 a Day***, sociologist Kathryn Edin and poverty researcher Luke Shaefer examine the lives of nearly 3 million kids in the US growing up in homes that have almost no cash income. Then in ***Portfolios of the Poor***, economist Jonathan Morduch and a team of economists and microfinance experts broaden the investigation to Bangladesh, India, and South Africa. Both books will help us to understand how a billion people get by every day with so little. 

Next, we will sample from a few books that will give us an opportunity to consider why some people and places are poor and sick in the first place. For starters, we'll read two chapters from Sir Angus Deaton's book, ***The Great Escape***, to get a brief history of poverty and development. Then we'll consider dualing perspectives on the cause of poverty. In ***Bottom Billion***, economist Paul Collier suggests that there are four traps that put and keep people in poverty: civil war, the resource curse, the problem of being landlocked, and bad governance. Just as you are starting to nod your head in agreement, economist Daron Acemoglu and political scientist James Robinson will make you think again with their book, ***Why Nations Fail***, that puts the blame on economic and politicial institutions instead. Turning then to health, we'll read the ideas of two people who have given a lot of thought to the question of why people get sick and die. In ***Epic Measures***, journalist Jeremy Smith tells the story of Dr. Chris Murray and his quest to quantify death and disability on a scale never before attempted. In ***Infections and Inequalities***, Paul Farmer makes his second appearance in the semester to help us understand why it takes more than biology to understand infectious diseases.

In the final module of the semester, we will examine the search for "what works" to end poverty improve global health. First we'll consider the role of foreign aid in bringing about ***The End of Poverty***. In this book, economist Jeff Sachs gives us an inspiring look at how we could end extreme poverty by 2025 if we just spent more money. This idea was put to the test through the Millennium Villages Project, and journalist Nina Munk takes us on a critical journey of the results in her book ***The Idealist***. We'll wrap up with ***Poor Economics*** by Esther Duflo and Abhijit Banerjee, two of the founders of the Abdul Latif Jameel Poverty Action Lab. This book will take us on a fascinating tour of evidence from recent randomized controlled trials that will reveal keen insights into the the lives of the poor and suggest steps for turning evidence into action.

# What You'll Watch

We will screen two films this semester: 

- ***Good Fortune***, a documentary about the recipients of foreign aid in Kenya and the flipside of good intentions; and

- ***Bending the Arc***, a documentary about Paul Farmer and the work of Partners In Health to bring world-class healthcare to everyone, everywhere. 

# What You'll Do

## Format

In this course I'll ask you to learn how to explore data and share what you are thinking and learning through individual writing assignments and group projects. Data exploration, writing, and speaking are three fundamental skills you need to master during your time at Duke, and I want to help you get started. Here's what you can expect:

In the first module, I'll teach you how to search the literature effectively, organize your writing, and access data. Follow the instructions to prepare for each session, and come to class with a laptop.

In the remaining modules, we'll discuss assigned books and readings on Tuesdays and complete a data tutorial in class on Thursdays (so bring your laptop). In the last week of each module, Tuesday will be a writing workshop, and Thursday will be a presentation workshop.

Prior to each writing workshop, you will submit a draft that will be reviewed by two students who will prepare written feedback. The three of you will meet during class to review your draft and peer ideas for improvement. You will then take the feedback you receive in writing and in person and prepare a final draft for a course grade. 

In preparation for the presentation workshops, you a group of 3-4 other students will meet to prepare a short presentation on an assigned topic. You'll remain with this group thoughout the semester and give a total of three presentations. You will receive feedback on your presentation style from your audience, and you will give it in turn. 

## Requirements

### Class Participation (30%)

Your participation grade will be determined by your attendance and contributions to class activities (see [Duke's definition of a seminar](http://trinity.duke.edu/undergraduate/academic-policies/seminars)). You should be prepared to comment on every reading in case I decide to call on you in class. I will incorporate pop quizzes and other assignments if I feel there is a need to further incentivize students to keep up with the readings.

### Writing Workshops (20%)

You will participate in three writing workshops this semester. Prior to each workshop, you will share a draft with me and two other students, and you will provide written feedback for these students. 

### Presentation Workshops (20%)

Your group will prepare three 10-minute presentations this semester. After each workshop, you will provide written feedback for one other group.

### Final Paper (30%)

There is no final exam scheduled for finals week. Instead, you submit a final paper by 9am ET on Thursday December 14. I will share details about the structure and format of this paper.

I encourage you to consult the Writing Studio when you are preparing your final. In addition to offering 1-on-1 consultations, the Writing Studio also publishes [helpful resources](http://twp.duke.edu/writing-studio/resources) that will help you to improve your drafts, such as [this collection](http://twp.duke.edu/writing-studio/resources/working-with-sources) on working with sources. Avoid plagiarism and [know when to quote (rarely) and when to paraphrase (often)](http://twp.duke.edu/uploads/media_items/quotations.original.pdf).

# What You'll Need

## Books

We'll read the majority of each book listed below, so you should make sure you have access to a copy:

1. ***$2.00 a Day: Living on Almost Nothing in America***, Kathryn J. Edin, H. Luke Shaefer ([Amazon](http://amzn.to/29H5ubP)/on reserve)
2. ***Portfolios of the Poor***, Daryl Collins, Jonathan Morduch, Stuart Rutherford, Orlanda Ruthven ([Amazon](http://amzn.to/29NLQP0)/[Duke eBook](http://search.library.duke.edu/search?id=DUKE004242530))
3. ***The End of Poverty***, Jeff Sachs ([Amazon](http://www.amazon.com/End-Poverty-Economic-Possibilities-Time-ebook/dp/B007ZHC6H6/ref=sr_1_1?s=digital-text&ie=UTF8&qid=1406223134&sr=1-1&keywords=the+end+of+poverty)/on reserve)
4. ***The Idealist***, Nina Munk ([Amazon](http://www.amazon.com/Idealist-Jeffrey-Sachs-Quest-Poverty-ebook/dp/B00BVJG2LK/ref=sr_1_1?s=digital-text&ie=UTF8&qid=1406223220&sr=1-1&keywords=the+idealist)/on reserve)
5. ***Poor Economics***, Abhijit Banerjee and Esther Duflo ([Amazon](http://www.amazon.com/Poor-Economics-Radical-Rethinking-Poverty-ebook/dp/B007CI81IQ/ref=sr_1_1?s=digital-text&ie=UTF8&qid=1406223382&sr=1-1&keywords=poor+economics)/[Duke eBook](https://search.library.duke.edu/search?id=DUKE006411427))

All other assigned readings will be available to you via Piazza.

## Software

In Module 1, you will be instructed to download and install R, RStudio, and Zotero. All are free to download and use. You'll also need to sign up for access to Google Docs and Piazza.

# Policies

- You are permitted 2 unexcused absences throughout the semester. Beyond that, each unexcused absence will result in your overall grade being lowered by 1-step (e.g., A+ to A). Coming late to class counts as 0.5 unexcused absences.

- Officially, Duke permits students to miss work due to absence from class in four circumstances: illness; personal emergencies; religious observance; and varsity athletic participation. Please take a moment to [read](http://trinity.duke.edu/undergraduate/academic-policies/class-attendance-and-missed-work) how Duke defines each circumstance. Missed work associated with any other absence is not covered by this policy and will be considered on a case-by-case basis.

- Late assignments will lose 15% of possible points initially. If you fail to turn in an assignment within 12 hours of the deadline, you will lose all possible points. I will use Google Docs version history to determine document status at submission deadlines.  

- Students should abide by the [Duke Community Standard](http://studentaffairs.duke.edu/conduct/about-us/duke-community-standard) at all times. If a questionable circumstance arises, do not hesitate to seek my guidance (before is always better than after).

- Your final grade will be a weighted average of each requirement. If you are in between grades, and if the difference is less than or equal to 0.5, your score will round up (e.g., 97.5 rounds up to 98). Ranges for letter grades will be set at the end of the semester, and grades may be curved. Cumulative scores of at least 90, 80, and 70 will be guaranteed at least an A-, B-, and C-, respectively.

- Any student with a documented disability needing academic adjustments or accommodations should speak with me during the first two weeks of class. All discussions will remain confidential. Students with disabilities will also need to contact the Student Disability Access Office.
